version: "3.9"

services:
  gerrit:
    build: 
      context: build/gerrit
      args:
        - GERRIT_VERSION
    image: gerrit
    volumes:
      - gerrit-data:/data
      - ./tmp:/tmp-data
    env_file:
      - .env
    ports:
      - target: 8080
        # published: 8080-9080
        published: 8080
        protocol: tcp
      - target: 29418
        published: 29418
        protocol: tcp
      - target: 389
        published: 1389
        protocol: tcp
volumes:
  gerrit-data:
